sudo: required
services:
  - docker
env:
  global:
    - BASE_IMAGE=golang:1.11.1-alpine3.7
    - IMAGE_NAME=onlinecode
before_install:
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - sudo apt-get update
  - sudo apt-get -y install docker-ce
before_script:
  - docker pull "$BASE_IMAGE"
script:
  - docker build -t ${IMAGE_NAME}:latest .
after_script:
  - docker images
before_deploy:
  - docker login -u ${DOCKER_LOGIN_USER_NAME}  -p ${DOCKER_LOGIN_PASSWORD}
  - docker tag "${IMAGE_NAME}:latest" "${DOCKER_REPO_NAME}/${IMAGE_NAME}:latest"
  - docker tag "${IMAGE_NAME}:latest" "${DOCKER_REPO_NAME}/${IMAGE_NAME}:${TRAVIS_BUILD_NUMBER}"
deploy:
  skip_cleanup: true
  provider: script
  script: docker push "${DOCKER_REPO_NAME}/${IMAGE_NAME}:dev-latest" && docker push "${DOCKER_REPO_NAME}/${IMAGE_NAME}:dev-${TRAVIS_BUILD_NUMBER}"
  on:
    branch: master
#notifications:
 # email: false