version: "3"
services:
  web:
    ports:
      - "8086:8086"
    image: iamwwc/onlinecode:latest
    volumes:
      - .:/go/src/onlinecode
      - onlinecodetemp:/onlinecodetemp
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - onlinecode-net
    container_name: onlinecodeapp
    #command: ["sh","-c", "tail -f /dev/null & /go/src/onlinecode/scripts/onlinecode"]
  db:
    image: mysql:8.0
    container_name: onlinecodedb
    volumes:
      - onlinecode-database:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: mysqlrootpassword
      MYSQL_PASSWORD: mysqlpassword
      MYSQL_USER: mysql
      MYSQL_DATABASE: onlinecode
    ports:
      - "3300:3306"
    networks:
      - onlinecode-net

networks:
  onlinecode-net:
    driver: bridge

volumes:
  onlinecodetemp:
  onlinecode-database: