version: "3"
services:
#  web:
#    ports:
#      - "8086:8086"
#    image: iamwwc/onlinecode:latest
#    volumes:
#      - .:/go/src/onlinecode
#      - onlinecodetemp:/onlinecodetemp
#      - /var/run/docker.sock:/var/run/docker.sock
#    environment:
#      CODE_WORK_DIR: /go/src/chaochaogege.com/onlinecode
#    networks:
#      - onlinecode-net
#    container_name: onlinecodeapp
  db:
    image: mysql:8.0
    container_name: onlinecodedb
    volumes:
      - onlinecode-database:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: mysqlrootpassword
      MYSQL_PASSWORD: mysqlpassword
      MYSQL_USER: mysql
      MYSQL_DATABASE: onlinecode
    ports:
      - "3300:3306"
    networks:
      - onlinecode-net
#  debug:
#    image: ccr.ccs.tencentyun.com/wwc-docker-images/onlinecode:golang-delve
#    ports:
#      - "8086:8086" #api port
#      - "8088:8088" #debug server
#    container_name: debugserver
#    volumes:
#      - ./:/go/src/chaochaogege.com/onlinecode
#      - onlinecodetemp:/onlinecodetemp
#      - /var/run/docker.sock:/var/run/docker.sock
#    networks:
#      - onlinecode-net
#    environment:
#      CODE_WORK_DIR: /go/src/chaochaogege.com/onlinecode
networks:
  onlinecode-net:
    driver: bridge

volumes:
  onlinecodetemp:
  onlinecode-database: